export enum Collection {
    AAMBIENTE_E_SAUDE = 1,
    CONTROLE_E_PROCESSOS_INDUSTRIAIS,
    DESENVOLVIMENTO_EDUCACIONAL_E_SOCIAL,
    ETEC_IDIOMAS,
    GESTAO_E_NEGOCIOS,
    INFORMACAO_E_COMUNICACAO,
    INFRAESTRUTURA,
    MILITAR,
    PESQUISAS_EM_CIENCIAS_E_TECNOLOGIAS_NA_EDUCACAO,
    PESQUISAS_EM_EAD_TIC,
    PRODUCAO_ALIMENTICIA,
    PRODUCAO_CULTURAL_E_DESIGN,
    PRODUCAO_INDUSTRIAL,
    PROFUNCIONARIO,
    RECURSOS_NATURAIS,
    SEGURANCA,
    TURISMO_HOSPITALIDADE_E_LAZER
}